name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}" 
        //https://docs.github.com/en/actions/reference/workflows-and-actions/contexts