##//vnd
name: Deployment Exercise 1
on: 
 pull_request:
  types:
   - opened
 workflow_dispatch:
 push:
   branches:
     - main
     - dev-*
     - new-*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v7
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: upload-vnd
          path: |
            dist
            package.json
      - name: download artifact
        uses: actions/download-artifact@v8
        with:
          name: upload-vnd
      - name: output
        run: ls 
      - name: Deploy code
        run: echo "Deploying..."
